### ISSUE TITLE
Checking for file existence is an anti-pattern

### ISSUE THREAD

**Issue by LinusU** [joakimbeng/create-file#1]
Checking if a file exists and then, if not, writing to it is an anti-pattern because it introduces a very real possibility of race conditions.

I would look into using the `O_EXCL` flag instead. When opening a file for writing in exclusive mode, it will fail if the file already exists. In Node that flag is used by passing an extra `x` to the `flag` parameter.

The error returned if the file exists will be `EEXIST` (check `err.code === 'EEXIST'`).

**Comment by joakimbeng** [comment]
Yeah you're right. For my use case I won't ever run into this issue, but to make this a more general module I've now changed the behavior. Released as `1.0.1`.

**Comment by LinusU** [comment]
Nice :+1:
